### ISSUE TITLE
Error while merging

### ISSUE THREAD

**Issue by MarianoRyu** [Fragjacker/DoW-Mod-Manager#22] opened 2020-09-26 18:43 UTC
It does this automatically while merging, and I have to fix the .module file manually.

![DoW Mod Manager v2 1 2 26_9_2020 15_41_32](https://user-images.githubusercontent.com/71943317/94347941-dfd8c680-000e-11eb-8805-63bd1e1eaae6.png)

Also, it doesn't seem to accept more than 20 mods?

**Comment by Fragjacker** [comment] 2020-09-26 18:50
@MarianoRyu What exactly were the steps you were doing to reproduce this issue?

> Also, it doesn't seem to accept more than 20 mods?

Which one accepts max 20 mods? The Mod Manager or the Mod Merger?

**Comment by MarianoRyu** [comment] 2020-09-26 18:53
I'm trying to do two things:

1 - I want to merge mods with the Codex 4.0 mod (I have done that in the past manually, and it seems to work fine, at least until 20 mods are reached).

2 - I want to start the Unification mod directly, and it crashes on startup. I can guarantee all these race mods work stand-alone.

I opened the merge mod option, opened up codex 4.0, added the mods I wanted to add, and clicked Save, and that's what came out.

The game won't start after I add the 21st mod, either in Codex or Unification.

**Comment by Fragjacker** [comment] 2020-09-28 11:31
Alright I have confirmed that the Mod Merger was completely busted. It produced the issue you reported even when flat out saving the same file without making any changes. However I was able to pinpoint the cause of this and made a fix for this bug. Could you confirm that it does indeed work properly now? Here's the new build of it @MarianoRyu :

[DoW Mod Manager v2.1.3.zip](https://github.com/Fragjacker/DoW-Mod-Manager/files/5291869/DoW.Mod.Manager.v2.1.3.zip)

Once you confirm this bug to be fixed I can push the new build proper and update all clients.

Make sure you use a fresh un-corrupted .module file to test this since the ones produced by the issue you reported are blasted.

**Comment by MarianoRyu** [comment] 2020-09-28 21:28
Can confirm it works just fine now. Thank you very much for your attention!

**Comment by Fragjacker** [comment] 2020-09-29 10:09
Alright this issue was fixed in commit c5bd09635999d55c6dd7bcb8b57b323065bc8f18 and release v2.1.3 upwards.

Closed.

**Closed as completed by Fragjacker** 2020-09-29 10:09 UTC
Labels: bug
